// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4BT6v5ohbtXdqiKuH7wM8HXAzSf9ydu8',
    appId: '1:1020421031874:web:45266de49e7a59bf29785b',
    messagingSenderId: '1020421031874',
    projectId: 'civiclink-25',
    authDomain: 'civiclink-25.firebaseapp.com',
    storageBucket: 'civiclink-25.firebasestorage.app',
    measurementId: 'G-8ZHWFF874V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6RC9byzUOW0Jnm_ajmRCbE93Hyobvhyk',
    appId: '1:1020421031874:android:017c984a8836529d29785b',
    messagingSenderId: '1020421031874',
    projectId: 'civiclink-25',
    storageBucket: 'civiclink-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-84lxhzimUsd3g_Mwt08RB1iMvRb-udw',
    appId: '1:1020421031874:ios:7e0997eb0905430029785b',
    messagingSenderId: '1020421031874',
    projectId: 'civiclink-25',
    storageBucket: 'civiclink-25.firebasestorage.app',
    iosBundleId: 'com.civiclink.civiclink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-84lxhzimUsd3g_Mwt08RB1iMvRb-udw',
    appId: '1:1020421031874:ios:7e0997eb0905430029785b',
    messagingSenderId: '1020421031874',
    projectId: 'civiclink-25',
    storageBucket: 'civiclink-25.firebasestorage.app',
    iosBundleId: 'com.civiclink.civiclink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4BT6v5ohbtXdqiKuH7wM8HXAzSf9ydu8',
    appId: '1:1020421031874:web:260fb688a0010c7029785b',
    messagingSenderId: '1020421031874',
    projectId: 'civiclink-25',
    authDomain: 'civiclink-25.firebaseapp.com',
    storageBucket: 'civiclink-25.firebasestorage.app',
    measurementId: 'G-E47N87SDCS',
  );
}
